#!/usr/bin/zsh

inactivity_minutes=10
screensaver_fade_in_seconds=30
xset s $(( $inactivity_minutes * 60 )) $screensaver_fade_in_seconds
dpms_inactivity_minutes=$(( $inactivity_minutes + 1 ))
dpms_inactivity_seconds=$(( $dpms_inactivity_minutes * 60 ))
xset dpms $dpms_inactivity_seconds $dpms_inactivity_seconds $dpms_inactivity_seconds

xsetroot -cursor_name left_ptr -solid '#3f3f3f'
xrdb-reload

XSECURELOCK_DIM_COLOR='#7f9f7f' XSECURELOCK_SHOW_HOSTNAME=0 XSECURELOCK_SHOW_USERNAME=0 XSECURELOCK_DIM_TIME_MS=30000 xss-lock -n /usr/lib/xsecurelock/dimmer -l -- /usr/bin/xsecurelock &

home.d-file () {
    local rel_path=$1
    local abs_path=$HOME_D/$rel_path
    local abs_path2=$HOME_D/profile/$rel_path
    if [[ -e $abs_path ]]; then
        echo $abs_path
    elif [[ -e $abs_path2 ]]; then
        echo $abs_path2
    else
        echo Nothing
    fi
}

source-home.d () {
    local rel_path=$1
    local abs_path=$(home.d-file $rel_path)
    if [[ $abs_path != Nothing  ]]; then
        source $abs_path
    fi
}

source-home.d x11/monitors

exec $HOME_D_XMONAD
