#!/usr/bin/env bash

set -u

matches () {
    local expr="$1"

    local unified_diff=$(git diff --cached --unified=0)
    local no_filename_diff=$(echo "$unified_diff" | sed '/^diff --git/,/^+++/d;')
    local added_lines=$(echo "$no_filename_diff" | sed --quiet 's/^+//p')

    echo "$added_lines" | grep --quiet "$expr"
}

preCommitReject () {
    if [[ $(git config --get homeD.rejectOnMatch) == true ]]; then
        expressions=($(git config --get-all homeD.rejectExpressions))

        for expr in ${expressions[@]}; do
            if matches "$expr"; then
                echo "Commit rejected as it matches '$expr'"
                exit 1
            fi
        done
    else
        exit 0
    fi
}

main () {
    preCommitReject
}

main
