#!/usr/bin/env zsh

FINSDIR="${FINSDIR:-$HOME_D/fins}"
BINDIR="$FINSDIR/bin"

typeset -A fins

for file in $FINSDIR/funs.d/?*.zsh ; do
    echo "Working on $file"
    source "$file"

    mkdir -p "$BINDIR"

    set -A function_list $(functions | sed -n 's/^\([^ ]\+\) () {$/\1/p')

    for fun in $function_list; do
        if [[ $fun =~ '^__' ]]; then
            continue
        fi

        fins[$fun]=1

        fin="$BINDIR/$fun"
        echo "  Creating $fin"
        cat > "$fin" <<EOF
#!/usr/bin/env zsh

set -e
set -u
# look into zshparseopt instead of relying on set -u

source "$file"

$fun "\$@"
EOF
        chmod u+x "$fin"
    done

    # Also unfunction the auxiliary functions ending with an underscore
    for fun in $function_list; do
        echo "  Removing function $fun from scope"
        unfunction $fun
    done
done

typeset -a existing_fins
existing_fins=($(cd $BINDIR; ls))

echo "Checking for fins to remove"
for existing_fin in ${existing_fins[@]}; do
    if [[ ${fins[$existing_fin]} != 1 ]]; then
        fin="$BINDIR/$existing_fin"
        echo "  Removing $fin"
        rm "$fin"
    fi
done
