#!/usr/bin/zsh

FINSDIR="${FINSDIR:-$HOME_D/fins}"

for file in $FINSDIR/funs.d/?*.zsh ; do
    echo "Working on $file"
    source "$file"

    mkdir -p "$FINSDIR/bin"

    set -A function_list $(functions | sed -n 's/^\([^ ]\+\) () {$/\1/p')

    for fun in $function_list; do
        if [[ $fun =~ '^__' ]]; then
            continue
        fi

        fin="$FINSDIR/bin/$fun"
        echo "  Creating $fin"
        cat > "$fin" <<EOF
#!/usr/bin/zsh

set -e
set -u
# look into zshparseopt instead of relying on set -u

source "$file"

$fun "\$@"
EOF
        chmod u+x "$fin"
    done

    # Also unfunction the auxiliary functions ending with an underscore
    for fun in $function_list; do
        echo "  Removing function $fun from scope"
        unfunction $fun
    done
done
